version: "3"
services:
    mysql:
        image: mysql:8.0
        ports:
            - 3307:3306
        environment:
            - MYSQL_DATABASE=zengym
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./backup_data/db:/var/lib/mysql
        networks:
            - sportif_network
    frontend:
        image: medali99/frontend
        ports:
            - 4444:4200
        # environment:
        #     - BACKEND_API_URL=http://backend:8081  # Pass backend URL to the frontend
        depends_on:
            - backend
        networks:
            - sportif_network        
    backend:
        image: medali99/backend
        # container_name: backend
        ports:
            - 8090:8081
        depends_on:
            - mysql
        networks:
            - sportif_network
       






    reverseproxy:
     image: nginx:alpine
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       - /etc/letsencrypt/live/dalidev.ddns.net/fullchain.pem:/etc/ssl/certs/fullchain.pem
       - /etc/letsencrypt/live/dalidev.ddns.net/privkey.pem:/etc/ssl/private/privkey.pem
     depends_on:
       - frontend
       - backend
     networks:
       - sportif_network
          
networks:
    sportif_network:
        driver: bridge
#aaaaa