version: "3"
services:
    mysql:
        ports:
            - 3307:3306
        container_name: mysqlcontainer
        environment:
            - MYSQL_ROOT_PWD=root
            - MYSQL_DB=zengym
        volumes:
          - ./backup_data/db:/var/lib/mysql
        image: mysql
        networks:
          - sportif_network
          
    backend:
        ports:
            - 8090:8082
        container_name: backend
        environment:
            - MYSQL_HOST=mysqlcontainer
            - MYSQL_PORT=3306
            - MYSQL_DB_NAME=zengym
            - MYSQL_PWD=root
        build: ./projet_pfe1-1/Dockerfile
        networks:
          - sportif_network
       
    frontend:
        ports:
            - 4444:4200
        container_name: frontend
        networks:
            - sportif_network
        build: ./ConceptSportifFrontEnd/Dockerfile
    reverseproxy:
     image: nginx:alpine
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       - /etc/letsencrypt/live/dalidev.ddns.net/fullchain.pem:/etc/ssl/certs/fullchain.pem
       - /etc/letsencrypt/live/dalidev.ddns.net/privkey.pem:/etc/ssl/private/privkey.pem
     depends_on:
       - frontend
       - backend
     networks:
       - sportif_network
          
networks:
    sportif_network:
        driver: bridge