name: CI/CD Pipeline

on:
  push:
    branches: ["dali"]
  pull_request:
    branches: [ "master" ]

jobs:
  continuous_integrate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Transfer all project files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: .
          target: /home/ubuntu/deoloy/

      - name: Debug SSH Connection (Optional)
        run: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP_ADDRESS }} "echo 'SSH Connected Successfully'"


      - name: Debug directory structure
        run: |
          ls -R

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: medali99/backend
          context: ./projet_pfe1-1

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: medali99/frontend
          context: ./ConceptSportifFrontEnd

  continuous_deployment:
    needs: continuous_integrate
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Execute SSH Commands for Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/deoloy/
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
